workflows:
  ios-release:
    name: Build iOS IPA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --release --no-codesign
      - mkdir -p $HOME/artifacts
      - find build -type f -name "*.ipa" -exec cp {} $HOME/artifacts/ \;
      - ls -lh $HOME/artifacts/
    artifacts:
      - $HOME/artifacts/*.ipa
