workflows:
  ios-release:
    name: Build iOS IPA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --release --no-codesign
      - ls -la build/ios/ipa/  # DEBUG: muestra dónde está el IPA
    artifacts:
      - build/ios/ipa/*.ipa    # RUTA RELATIVA CORRECTA (desde raíz del proyecto)
