workflows:
  ios-release:
    name: Build iOS IPA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --release --no-codesign
      - mkdir -p \$FCI_BUILD_DIR/artifacts
      - find build -name "*.ipa" -type f -exec cp {} \$FCI_BUILD_DIR/artifacts/ \;
      - ls -lh \$FCI_BUILD_DIR/artifacts/
    artifacts:
      - artifacts/*.ipa
