workflows:
  ios-release:
    name: Build iOS
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --release
      - find . -name "*.ipa" -print -exec cp {} $FCI_BUILD_DIR 2>/dev/null \;
    artifacts:
      - "*.ipa"
