workflows:
  ios-release:
    name: Build iOS IPA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --release --no-codesign 2>&1 | tee build.log
      - find . -name "*.ipa" -type f -print || echo "IPA not found yet"
    artifacts:
      - "**/*.ipa"
      - "build.log"
